services:
  reviewer-assigner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reviewer-assigner
    ports:
      - ${PORT}:8080
    environment:
      CONFIG_PATH: ./config/config.yaml
    depends_on:
      db:
        condition: service_healthy
      goose:
        condition: service_completed_successfully

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5

  goose:
    build:
      context: .
      dockerfile: Dockerfile.goose
    environment:
      GOOSE_DBSTRING: ${GOOSE_DBSTRING}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
